services:
  - type: web
    name: zendesk-telegram-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ZENDESK_EMAIL
        sync: false
      - key: ZENDESK_TOKEN
        sync: false
      - key: ZENDESK_SUBDOMAIN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PORT
        value: 8000
